development:
  cloud_name: <%= Figaro.env.cloud_name %>
  api_key: <%= Figaro.env.api_key %>
  api_secret: <%= Figaro.env.api_secret %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= Figaro.env.cloud_name %>
  api_key: <%= Figaro.env.api_key %>
  api_secret: <%= Figaro.env.api_secret %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= Figaro.env.cloud_name %>
  api_key: <%= Figaro.env.api_key %>
  api_secret: <%= Figaro.env.api_secret %>
  enhance_image_tag: true
  static_image_support: false
